"""Canonical topic names used across modules."""

CLOCK = "/clock"
ODOM = "/odom"
SCAN = "/scan"
SCAN_FILTERED = "/scan_filtered"
MAP = "/map"
CMD_VEL = "/cmd_vel"
CAMERA_IMAGE = "/camera/image_raw"
CAMERA_INFO = "/camera/camera_info"
YOLO_ANNOTATED_IMAGE = "/human_yolo/annotated_image"
PERSON_AZIMUTH_RANGES = "/human_yolo/person_azimuth_ranges"
PERSON_LASER_MAP_CLOUD = "/human_yolo/person_laser_map_cloud"
SPEECH_TEXT = "/interaction/speech_text"
PARSED_INTENT = "/interaction/parsed_intent"
TASK_EVENTS = "/task/events"
TASK_STATUS = "/task/status"
