#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

require_ros
require_command colcon
prepare_output_dirs

cd "${ROS_WS}"
# symlink-install：install/share 下的 config、launch 等尽量链到源码，避免“只改了几行 yaml 忘了 colcon install”的运行时仍为旧副本
OPTS=(--symlink-install "$@")
colcon build "${OPTS[@]}"

# 生成「LLM 凭据」加载片段：之后只需 source 工作区 install/setup.bash，即可自动 source 仓库根目录的 local_llm.env（若存在）。
# 说明：colcon 每次会重写 install/setup.bash，故在每次成功 build 后按需重新追加钩子（通过 grep 避免重复块）。
_tj_llm_helper="${ROS_WS}/install/tj_source_local_llm.bash"
{
  echo "# Generated by scripts/build.sh — do not edit."
  printf 'export _TJ_ROBOT_ROOT=%q\n' "${PROJECT_ROOT}"
  echo 'if [[ -f "${_TJ_ROBOT_ROOT}/local_llm.env" ]]; then'
  echo '  set -a'
  echo '  # shellcheck disable=SC1091'
  echo '  source "${_TJ_ROBOT_ROOT}/local_llm.env"'
  echo '  set +a'
  echo 'fi'
  echo 'unset _TJ_ROBOT_ROOT'
} >"${_tj_llm_helper}"

SETUP_B="${ROS_WS}/install/setup.bash"
if [[ -f "${SETUP_B}" ]] && ! grep -qF 'tj_source_local_llm.bash' "${SETUP_B}"; then
  cat >>"${SETUP_B}" <<'HOOK'

# === TJ-Robot: optional local_llm.env (appended by scripts/build.sh) ===
_tj_llm_sh="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)/tj_source_local_llm.bash"
if [[ -f "${_tj_llm_sh}" ]]; then
  # shellcheck source=/dev/null
  source "${_tj_llm_sh}"
fi
unset _tj_llm_sh
# === end TJ-Robot ===
HOOK
fi

echo "Build complete. Source: ${ROS_WS}/install/setup.bash"
echo "  (若存在 ${PROJECT_ROOT}/local_llm.env，source 上述 setup.bash 时会自动加载 TJ_LLM_* 变量。)"
