name: ros2-ci

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths ros_ws/src --ignore-src -r -y

      - name: Build (selected packages)
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros_ws
          colcon build --event-handlers console_direct+ --packages-up-to robot_bringup human_yolo_seg robot_tasks robot_interfaces robot_interaction robot_manipulation --cmake-args -DROBOT_INTERFACES_ENABLE_ROSIDL=ON

      - name: Test (selected packages)
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros_ws
          colcon test --event-handlers console_direct+ --packages-select robot_tasks
          colcon test-result --verbose
